### PR TITLE
A function that checks for namespace inheritance.

### PR DESCRIPTION
**Pull request by heliocentrist**
When dealing with a hierarchy of namespaces it is useful to be able to check if the namespace A you're dealing with is a child of another namespace B. This way you can safely use functions from namespace B without being afraid of type errors.

An example and a test are included.

### CODE REVIEW

**Comment by jwoudenberg** [comment]
Thanks for your PR, but I think there is an easier way to achieve this. Considering namespaces form a prototype chain, we can simply use [`isPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf):

```js
var subNamespace = virgilio.namespace('foo.bar.sub');
virgilio.foo.isPrototypeOf(subNamespace); //-> true
```

But to be honest, I wonder if I'd ever do this. If I use a non-existing namespace, I want my application to crash to tell me I made a mistake. Or do you see a use case where this is undesired behavior?

**Comment by heliocentrist** [comment]
Fair enough, this is a better way indeed. I was focusing on checking a namespace against a string path, so using the prototype chain slipped my mind.

I would use this check for the same reason the function arguments are checked. This way, instead of waiting for a crash to happen eventually, maybe on a rarely used code path, you will get a predictable error right away.

**Comment by lucamaraschi** [comment]
@heliocentrist for predictable error do you mean *"readable"* instead?

**Comment by heliocentrist** [comment]
@lucamaraschi yes, I think the error should be self-explanatory, but also it should be thrown as early as possible. Consider this case:

```javascript
virgilio.defineAction$('endpoint.mailer.send', function() { [...] });

var endpoint = virgilio.namespace$('endpoint');
var mailer = virgilio.namespace$('endpoint.mailer');

var localMailer = mailer.namespace$('local');
var internationalMailer = mailer.namespace$('international');

// Trashcan is an endpoint, but not a mailer
var trashcan = endpoint.namespace$('trashcan');

function dispatchMail(mail, localMailer, internationalMailer, trashcan) {
	
	if (mail.isLocal()) {  
		// In most cases our mail is local
		localMailer.send(mail);   // OK
	} else if (mail.isInternational()) {  
		// In some cases our mail is international
		internationalMailer.send(mail);    // OK
	} else {
		// In rare cases, we don't know what to do,
		// so it goes to the trashcan
		trashcan.send(mail);	// Crash: trashcan is not a mailer.
	}
}
```

In this example, I will get a crash only in a rare case of mail without address. I'd like to be able to check in the beginning of the function that my trashcan actually supports methods from the 'mailer' namespace.

Granted, this is a weird example, but I hope it illustrates my point somewhat.

**Pull request closed without merging**
