### PR TITLE
aded fibbonaci sequencer

### PR DESCRIPTION
**Pull request by DesignFront**
aded fibbonaci sequencer

### CODE REVIEW

**Comment by lucamaraschi** [comment]
Can you please explain the reason why you removed generators?

**Comment by DesignFront** [comment]
It was throwing me an error, couldn't continue.
And you seem upset...

**Comment by edmunfollen** [comment]
Sorry for joining the conversation... just curious :)

@DesignFront: Which was that error? Maybe there's a fix for that (apart from just stop using generators)...

**Comment by DesignFront** [comment]
i get this error when running on node

https://www.dropbox.com/s/bv4exaozgh4as4n/Screenshot%202015-02-18%2011.41.52.PNG?dl=0

**Comment by edmunfollen** [comment]
I think I had the same error on node 0.10.x (generators not supported)
Updating to 0.12 or using 'gnode' solved that to me.

Which version of node are you using?

**Comment by DesignFront** [comment]
Now I'm at 0.10.36.
I'm trying to install the latest version, but mac is giving me a hard time.

tried: npm install -g npm@latest
but no luck...

**Comment by jwoudenberg** [comment]
Guys, can you tell me how you are running the tests? The generator example is skipped in the gulpfile, precisely because generators aren't commonly supported yet. Is there any specific actions you took that resulted in this error?

**Comment by edmunfollen** [comment]
I run the generators example manually. Just playing with it :)

@DesignFront: I installed 'n' (https://github.com/tj/n). So far so good. Now I can switch from nodeJS versions easily.

**Comment by jwoudenberg** [comment]
@edmunfollen, ah, perfect :). I was worried our test script was misbehaving.

**Comment by DesignFront** [comment]
@edmunfollen I updated node to 0.12 but still same error as before.

Also I am not able to get n working. maybe because i'm using zsh ?

**Comment by lucamaraschi** [comment]
@DesignFront is not a matter of being upset but just understanding the reason why things are done...

**Comment by NinjaTux** [comment]
@edmunfollen you can run node with harmony flags if you want to test generators

**Comment by edmunfollen** [comment]
@NinjaTux: Indeed, on node 0.11-12. On 0.10.x generators are just not supported.
@DesignFront: Regarding zsh, I could install 'n' through zsh. No problems. If you have problems with it, just forget that and run your new nodeJS 0.12 with the --harmony flag (as NinjaTux pointed at)

**Pull request closed without merging**
